FROM python:3.4-slim

RUN apt-get update -y \
        && apt-get install -y curl \
        && apt-get clean

RUN mkdir -p ~/.clusterrunner/dist \
        && cd ~/.clusterrunner \
        && curl -L https://cloud.box.com/shared/static/2pl4pi6ykvrbb9d06t4m.tgz > clusterrunner.tgz \
        && tar -zxvf clusterrunner.tgz -C ./dist \
        && cp ./dist/conf/default_clusterrunner.conf clusterrunner.conf \
        && chmod 600 clusterrunner.conf \
        && rm -f clusterrunner.tgz

EXPOSE 43000 43001

ENTRYPOINT ["/root/.clusterrunner/dist/clusterrunner"]
