FROM python:3.4-slim

RUN apt-get update -y \
        && apt-get install -y gcc git \
        && apt-get clean

ADD . /src

RUN pip install --upgrade -r /src/requirements.txt

ENTRYPOINT ["/src/main.py"]
